### ISSUE TITLE
Name change profile migration not working correctly

### ISSUE THREAD

**Issue by dumptruckman** [Multiverse/Multiverse-Inventories#329]
It seems that when a player changes their name their inventories data is not being properly migrated. In addition to making this work, some improvements would be needed. We need to create a migrated profile directory to store backups of profiles that get migrated. That way in case anything goes wrong we can manually restore data from the backups.

**Comment by Ichikuro** [comment]
Still a bug.  Just caught it on my server.  Went to find old players files, and are gone due to it knowing to switch to the UUID but the name didnt carry the files over...I'm guessing?

**Comment by winnipeg21** [comment]
Sorry to revive old post. I too had/have this issue with players.

**Comment by SlimeDog** [comment]
I think it's safe to say that everyone does. Note that there is a PR pending.

**Comment by winnipeg21** [comment]
True, didn't see the PR on my phone lmao

**Comment by benwoo1110** [comment]
There is a test build here if you want to try https://github.com/Multiverse/Multiverse-Inventories/pull/362#issuecomment-648521734

**Comment by benwoo1110** [comment]
This PR #428 should have elevated most of the migration issue, do update to the latest test build to try. Appreciate anyone that happens to change their player name to report how it went.

**Comment by SlimeDog** [comment]
Thanks. I don't have any name changes pending. Hopefully, someone will.

**Comment by untuned** [comment]
Just had an issue with this, luckily I was able to restore their inventory from a backup, but does anyone have a solution to this?

**Comment by nicegamer7** [comment]
@untuned what version of MV Inventories were you using? This should be fixed as of 4.2.3, but if not, I had another unmerged change that could help.

**Comment by seema84** [comment]
so can we assume that mv inventories still can't deal with name changes?

**Comment by zax71** [comment]
Yes

**Comment by CloudeLecaw** [comment]
im using the last released version Multiverse-Inventories_4.2.6 i saw players inventories are saved with their name.. and or ith theire uuids?..

its confusing.. me

Here you see its stored by name..
![image](https://github.com/Multiverse/Multiverse-Inventories/assets/12080017/22572343-7c31-40be-9e5e-4209c9736a46)

and here by uuid...?
![image](https://github.com/Multiverse/Multiverse-Inventories/assets/12080017/ef78ca60-8594-414c-bfec-c5261b1327ca)


so if i change the name... does it convert this or renmae the files? or does it snyc with the players information stored in uuid?

its confusing me a bit..

**Comment by VipelyRS** [comment]
> im using the last released version Multiverse-Inventories_4.2.6 i saw players inventories are saved with their name.. and or ith theire uuids?..
> 
> its confusing.. me
> 
> Here you see its stored by name.. ![image](https://private-user-images.githubusercontent.com/12080017/280614642-22572343-7c31-40be-9e5e-4209c9736a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MDc1MTksIm5iZiI6MTcxMDgwNzIxOSwicGF0aCI6Ii8xMjA4MDAxNy8yODA2MTQ2NDItMjI1NzIzNDMtN2MzMS00MGJlLTllNWUtNDIwOWM5NzM2YTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAwMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMDFkNWUzYTljNGNlMDJkMzllOWVmNjMwMmFhZGFkNzk3NTFiMzgwYTYwYzJkYjFlNzRhOTM2NDdiNmI2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Os90ngM7ycmI4Sbv3CzWSCDh4WeyYn4RgpvrkVCRfcQ)
> 
> and here by uuid...? ![image](https://private-user-images.githubusercontent.com/12080017/280614718-ef78ca60-8594-414c-bfec-c5261b1327ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MDc1MTksIm5iZiI6MTcxMDgwNzIxOSwicGF0aCI6Ii8xMjA4MDAxNy8yODA2MTQ3MTgtZWY3OGNhNjAtODU5NC00MTRjLWJmZWMtYzUyNjFiMTMyN2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAwMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOTI3MzFhNTQxN2IzNGExMDU2NjhhNDkyNzRkNzRjYzc2OTZjN2U2MjY0OGVhY2Q4YmIzNTA1N2QyMDY5NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QZSRDZ5MYLC6Epy-sUf0Cs_uP4a7YfbnkwKxqctZtmY)
> 
> so if i change the name... does it convert this or renmae the files? or does it snyc with the players information stored in uuid?
> 
> its confusing me a bit..
> 
> what might i can asume what will happen... player changes his name. and logs in world a he has his inventory and all fine.. now he change to world b that has a seperate inventory...
> 
> because of the namechange the plugin might not see this other inventory anymore because it was made for the old name?
> 
> or does it rename all playername files from all worlds when player logs in? would be a fair deal, even if direct uuid support would be better...

name changing wipes your inventory :/

**Comment by CloudeLecaw** [comment]
awww thats sad to hear.. people love name changing :-(

**Comment by RayLumi** [comment]
Is there a solution? I have the latest version and it still has this issue. 
Multiverse-Core Version: 4.3.12

**Comment by RayLumi** [comment]
changed to .13. Idk if its fixed though.

**Comment by benwoo1110** [comment]
This issue has been fixed it MV5
